# Generated by Django 4.0.4 on 2022-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utkwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('statement', models.TextField(blank=True)),
                ('nominator', models.CharField(max_length=50)),
            ],
        ),
    ]
