# Generated by Django 4.0.4 on 2022-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utkwebsite', '0002_serviceaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaward',
            name='statement',
            field=models.TextField(),
        ),
    ]
