# Generated by Django 4.0.4 on 2022-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utkwebsite', '0003_alter_serviceaward_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('nominator', models.CharField(max_length=50)),
            ],
        ),
    ]
