# Generated by Django 4.0.4 on 2022-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utkwebsite', '0004_letteraward'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('statement', models.TextField()),
                ('address_one', models.CharField(max_length=50)),
                ('address_two', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('nominator', models.CharField(max_length=50)),
            ],
        ),
    ]
